strictness: verylow
max-line-length: 80
uses:
    - flask
    - mongoengine
    - flask_mongoengine
    - markdown2
    - pygments
    - PyRSSGen2
    - WTForms
    - flask-script
    - pymongo
autodetect: true
